// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions dev = FirebaseOptions(
    apiKey: defaultTargetPlatform == TargetPlatform.android ? 'AIzaSyDBYx6JVLV-MW9E470Ik5HDaOYc5drub8w' : '',
    appId: defaultTargetPlatform == TargetPlatform.android ? '1:871652949217:android:b3ab8c0552d9c0ffb34ba0' : '',
    messagingSenderId: '871652949217',
    projectId: 'minimals-dev',
    // storageBucket: 'onfielddev.appspot.com',
    // iosBundleId: 'com.onfielddev.app'
  );

  static FirebaseOptions uat = FirebaseOptions(
    apiKey: defaultTargetPlatform == TargetPlatform.android ? 'AIzaSyCKsD1Z6g0NvsvgjFg8bzKDQjJZrO_FuVE"' : '',
    appId: defaultTargetPlatform == TargetPlatform.android ? '1:200660164325:android:9beaa0f9b7b090a996fe0c' : '',
    messagingSenderId: '200660164325',
    projectId: 'minimals-uat',
    // storageBucket: 'onfielddev.appspot.com',
    // iosBundleId: 'com.onfielddev.app'
  );

  static FirebaseOptions prod = FirebaseOptions(
    apiKey: defaultTargetPlatform == TargetPlatform.android ? 'AIzaSyAJwP_TiCTvh8dNV7jgeT6xDZuCEomDuUY' : '',
    appId: defaultTargetPlatform == TargetPlatform.android ? '1:375840358171:android:bb8f1b25f64a23ebf21dbe' : '',
    messagingSenderId: '375840358171',
    projectId: 'minimalsprod',
    // storageBucket: '',
    // iosBundleId: '',
  );
}
